CS-4820-Library-Project/COUNTER-5-Report-Tool

FetchData.py
Changes made in on_date_changed function to allow user to select different year and month
=> Year selector for different years

tests/test_AddVendorDialog.py
Implemented basics tests for AddVendorDialog
=> Testing add vendor dialog

ManageVendors.py
=> When user add new vendor, list is sorted A-Z

ManageDB.py, Search.py
fixed some errors with reading files into the database
=> add_search_functionality

FetchData.py, ImportFile.py
Cleaned up imports
copied fetch reports "file-open" behavior to file import
=> Fixed macOS open-file in Import

README.md, requirements.txt
=> Added requirements.txt & Install instructions

ui/MessageDialog.py, ui/MessageDialog.ui
=> Add button

tests/test_DisclaimerDialog.py, tests/test_FetchProgressDialog.py, tests/test_MessageDialog.py, tests/test_RemoveVendorDialog.py, tests/test_ReportResultWidget.py, tests/test_SearchAndClauseFrame.py, tests/test_SearchOrClauseFrame.py, tests/test_VendorResultsWidget.py, ui/MessageDialog.py, ui/MessageDialog.ui
=> Unit test for dialog/widget

Visual.py
Summary of Changes:
- Fixed bugs
- Clean code
- Implemented multi year charts
- Implemented dynamic data to excel for multi year
- Implemented for all charts: Vertical Bar, Horizontal Bar and Line charts
- Message notification in case user do not enter valid fields
- Only T0p 10/5 remaining to implement
=> Visual Updates

ManageDB.py, Search.py, Settings.py, VariableConstants.py
fixed an error and cleaned up a bit more
=> cleanup_search_interface

Costs.py, ManageDB.py, Search.py, VariableConstants.py, ui/CostsTab.py, ui/CostsTab.ui
added top_number_chart_search method
=> chart_search_db_changes

MainDriver.py, Settings.py
I am not quite sure is that what you need, tell me if it need to change anything
=> Signal on Setting change

Visual.py
- Added more comments
- Added comments for documentation
- Added completion message
- Tested thoroughly
=> Visual clean up

MainDriver.py, ManageVendors.py
Fix the problem: Implement the function of changes the name of the file and folder when the user is not using default report path
=> Fix the problem

Visual.py
- Diminish use of uppercase characters/wordings
=> Edit-Error-Completion-Messages

Visual.py
- Third column header name based on metric
=> Column-Header-Cost

MainDriver.py, Visual.py
- Add currency in charts and in excel file
=> Add-Currency-To-Charts

Costs.py, Search.py
repaints Search when removing AND
repaints Costs on Edit click
=> Force window to repaint upon removing AND, and Costs click Edit button

ui/FetchReportsTab.py, ui/FetchReportsTab.ui
Added space between fetch all and advanced fetch. Moved header text to center
=> Distinction between fetch all and advanced fetch

ui/ImportReportTab.py, ui/ImportReportTab.ui
Move import report select file button left
=> Move button

Visual.py
- Clean-up, added more comments
- Switched currency format
- Use new methods in ManageDB
- Modify documentation
- fill_names not called twice
=> Visual-Updates

ManageDB.py
added more comments, fixed emitting signal in setup_database when it shouldn't be, simplified backup_costs_data a bit
=> cleanup_managedb
